# Generated by Django 3.0.5 on 2020-05-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("city", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citydata",
            name="city_ibge_code",
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
