# Generated by Django 3.0.5 on 2020-04-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('estimated_population', models.IntegerField()),
                ('confirmed', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('deaths', models.IntegerField()),
            ],
        ),
    ]
