# Generated by Django 3.0.5 on 2020-04-22 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brazil", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statedata",
            old_name="estimated_population",
            new_name="estimated_population_2019",
        ),
    ]
