# Generated by Django 3.0.5 on 2020-04-23 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brazil", "0002_auto_20200422_1905"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="statedata", unique_together={("state", "date")},
        ),
    ]
