# Generated by Django 3.0.5 on 2020-04-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorldTotalData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirmed", models.IntegerField()),
                ("recovered", models.IntegerField()),
                ("deaths", models.IntegerField()),
                ("active", models.IntegerField()),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
