# Generated by Django 3.0.5 on 2020-04-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worldtotaldata",
            name="date",
            field=models.DateTimeField(unique=True),
        ),
    ]
