# Generated by Django 3.0.5 on 2020-04-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0002_auto_20200417_1419"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=60)),
                ("date", models.DateTimeField()),
                ("confirmed", models.IntegerField()),
                ("recovered", models.IntegerField()),
                ("deaths", models.IntegerField()),
                ("active", models.IntegerField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
