# Generated by Django 3.0.5 on 2020-04-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_countrydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydata',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='worldtotaldata',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
