# Generated by Django 3.0.5 on 2020-05-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0004_auto_20200429_2353"),
    ]

    operations = [
        migrations.AddField(
            model_name="countrydata",
            name="translated_country_name",
            field=models.CharField(default="none", max_length=60),
            preserve_default=False,
        ),
    ]
