# Generated by Django 3.0.7 on 2020-06-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_countrydata_translated_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydata',
            name='active',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='countrydata',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='countrydata',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='worldtotaldata',
            name='active',
            field=models.IntegerField(blank=True),
        ),
    ]
